[package]
name = "yocto-canvas"
version = "0.1.0"
authors = ["Zack <zphixon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: maybe wgpu-rs?
vulkano = "0.22.0"
vulkano-shaders = "0.22.0"
vulkano-win = "0.22.0"
winit = "*"
